export type {
  FoldMode,
  FoldState,
  NodeFlag,
  NodeKind,
  NodeLayout,
  NodeLink,
  OutlineFoldDoc,
  OutlineFrontmatter,
  OutlineNode,
  OutlineViewCallbacks,
  SealedPayload,
  TaskState,
  TaskToggleEvent,
  ToHtmlOptions,
} from './types.js';

export { parse, type ParseOptions } from './parse.js';
export { serialize } from './serialize.js';
export { toggleFold, isCollapsed, setExpandLevel, type ExpandLevel, type SetExpandLevelOptions } from './fold.js';
export { toHtml } from './toHtml.js';
export { canonTag, displayTags } from './tagSpelling.js';
export {
  captionToHtml,
  captionLinks,
  isAllowedCaptionUrl,
  parseHopTarget,
  parseNoteTarget,
  markdownLinkSpans,
  type CaptionHtmlOptions,
  type CaptionLink,
  type MarkdownLinkSpan,
  normalizeCaptionBreaks,
  captionVisibleText,
  captionStyleRuns,
  parseTinyHtmlRuns,
  tinyHtmlToSafeHtml,
  captionRunToTspanInner,
  type CaptionStyleRun,
} from './captionRich.js';
export {
  attachOutlineTree,
  expandLevelAnnouncement,
  foldToggleAnnouncement,
  type AttachOutlineTreeOptions,
  type AttachOutlineTreeHandle,
} from './attachOutlineTree.js';
export { ICONS, iconForNode, iconForTask, type IconName } from './icons.js';
export { hasSealed, isRemoteSealed, parseEncBody, formatEncTag } from './sealed.js';
export {
  demoSeal,
  demoOpen,
  DEMO_PASSPHRASE,
  DEMO_ALG,
} from './demoCrypto.js';
export {
  peelTrailingSections,
  parsePayloadMap,
  formatPayloadsBlock,
  collectPayloads,
  attachLayouts,
  attachPayloads,
  collectLayouts,
  formatLayoutBlock,
  parseLayoutBlock,
  parseLayoutMap,
  mergeFrontmatter,
  type LayoutMap,
} from './payloads.js';

export {
  assignPersistentId,
  previewPersistentId,
  mintNodeId,
  writtenId,
  indexOutline,
  linkPayloadNodes,
  nextAutoId,
  nodeMapKey,
  type AutoIdOptions,
} from './nodeAddress.js';

export type {
  ValidationSeverity,
  ValidationIssue,
  ValidationResult,
  ValidateOptions,
} from './validate.js';
export { validateDocument } from './validate.js';

export {
  createMapView,
  mountMapControls,
  mountMapLevels,
  autoPackPositions,
  pillSize,
  mapNodeClassNames,
  mapEdgeSvg,
  timeLeafLetterW,
  timeLeafPadLeft,
  timeLeafNodeFontPx,
  FOLD_SLOT,
  resolveMapFocus,
  mapNodeKeepsTextSelection,
  mapBackgroundPanSelection,
  clearSelectionForMapPan,
  mapPaintShouldRestoreFocus,
  mapKeyboardShouldHandle,
  mapHostOwnsFocus,
  mapPaintFocusAction,
  mapNodeDomId,
  isTaskEmphasis,
  foldCountLabel,
  type MapPoint,
  type MapViewBox,
  type MapLayout,
  type AutoPackOptions,
  type AutoPackResult,
  type PillSizeOptions,
  type PillSize,
  type MapViewOptions,
  type MapKeyboardWire,
  type MapViewHandle,
  type MapWidthStep,
  type NodeCopyResult,
  type MapFocusDirection,
  type ResolveMapFocusOptions,
} from './mapView.js';

export {
  bindTap,
  armSwallow,
  swallowConsumes,
  isTapPointer,
  isTouchTap,
  touchClickGuarded,
  nodeTapShouldActivate,
  SWALLOW_MS,
  SWALLOW_RADIUS_PX,
  TAP_SLOP_PX,
  TAP_CLICK_GUARD_MS,
  type SwallowRecord,
  type BindTapOptions,
} from './mapTap.js';

export {
  DEFAULT_WRAP_CH,
  DEFAULT_MAX_LINES,
  SOFT_SAFETY_MAX_LINES,
  SOFT_SAFETY_MAX_CHARS,
  TASK_LEAD,
  TASK_BOX,
  TASK_INSET,
  TASK_GAP,
  noteChipLabel,
  noteChipPieces,
  noteChipSpan,
  mapChipPieces,
  mapChipSpan,
  THREAD_CHIP_LABEL,
  THREAD_CHIP_H,
  type MapChipSpec,
  type MapChipPiece,
  CHAR_W,
  CODE_CHAR_W,
  lineAdvance,
  LINE_H,
  PILL_PAD_Y,
  MIN_TEXT_W,
  PILL_PAD_X,
  MORE_AFFORDANCE_H,
  resolveEffectiveMaxLines,
  wrapLines,
  measurePill,
  type WrapResult,
  type MeasurePillOpts,
  type MeasuredPill,
  FIT_TEXT_CH,
  naturalLineWidth,
  fitTextWidth,
  autoTextWidth,
  type FitMeasureOpts,
} from './mapLabel.js';
export {
  WIDTH_MIN_COL,
  WIDTH_MAX_COL,
  WIDTH_AUTO_TOLERANCE,
  WIDTH_STEP,
  WIDTH_TOAST_MS,
  SINGLE_LINE_MARGIN,
  W_AUTO_SINGLE_LINE,
  WIDTH_HELP_LINES,
  WIDTH_MENU_KEYS,
  WIDTHS_RESTORED,
  WIDTHS_REDONE,
  singleLineCap,
  singleLineWidth,
  fitTextEntry,
  oneLineEntry,
  stepEntry,
  sameWidth,
  siblingScope,
  widthToastText,
  widthPickAnnouncement,
  widthMenuKeyItem,
  type WidthEntry,
  type WidthPickKind,
} from './mapFit.js';

export {
  timeKindOf,
  timeLeafKind,
  timeLeafFontPx,
  timeLeafCaption,
  timeLeafAriaLabel,
  TIME_LEAF_FONT_SCALE,
  TIME_LEAF_PAD_Y,
  TIME_LEAF_PAD_X,
  TIME_LEAF_LETTER_GAP,
  TIME_LEAF_MAX_CH,
  TIME_LEAF_GAP_Y,
  TIME_LEAF_LETTER,
  TIME_LEAF_NAME,
  type TimeLeafKind,
} from './timeLeaf.js';

export {
  seedColdStartFold,
  seedDefaultFold,
  hasSavedFold,
  measureLineageHeight,
  DEFAULT_LINEAGE_HEIGHT_CAP,
  type DefaultFoldRule,
  type SeedDefaultFoldOptions,
} from './mapSeed.js';

export {
  foldLevelPicker,
  currentFoldLevel,
  foldLevelNeedsConfirm,
  foldChangeCount,
  foldLevelSkipsAnimation,
  foldLevelAnnouncement,
  wholeMapAnnouncement,
  FOLD_LEVEL_KEYS,
  LEVEL_ALL_CONFIRM_NODES,
  LEVEL_NO_FLIP_CHANGES,
  type FoldLevelKey,
  type FoldLevelItem,
  type FoldLevelPicker,
} from './foldLevel.js';

export {
  LEVEL_HOLD_MS,
  LEVEL_RING_MS,
  LEVEL_MENU_INSET,
  levelHoldSlop,
  startLevelHold,
  levelHoldMoved,
  levelHoldAt,
  levelHoldCancel,
  levelHoldRelease,
  levelContextAction,
  placeLevelMenu,
  levelMenuKeyAction,
  levelMenuInitialIndex,
  levelItemLabel,
  levelItemCount,
  levelConfirmLabel,
  levelKeepVisibleShift,
  renderLevelMenu,
  wholeMapLevelDoc,
  currentWholeMapLevel,
  WHOLE_MAP_LEVELS,
  type LevelHold,
  type LevelHoldPhase,
  type LevelContextAction,
  type LevelMenuKeyAction,
  type WholeMapLevel,
} from './foldLevelMenu.js';

export {
  linkPopWhere,
  renderLinkPop,
  renderLinkPopRows,
  captionLinkRows,
  noteLinkRows,
  noteLinkWhere,
  threadRows,
  opensNewWindow,
  LINK_EXT_ARROW,
  type LinkPopRow,
  placeLinkPop,
  LINK_POP_GAP,
  LINK_POP_INSET,
  type LinkPopView,
} from './linkPop.js';

export {
  noteUriTemplate,
  noteLinkHrefs,
  DEFAULT_NOTE_MAP_URI,
  DEFAULT_NOTE_DETAILS_URI,
  type NoteUriKey,
  type NoteUriOptions,
} from './linkTemplates.js';

export {
  savedViewStorageKey,
  viewPrefsStorageKey,
  viewSlotFor,
  isSameViewShape,
  captureSavedView,
  exactViewCam,
  anchoredFitViewCam,
  pickSavedView,
  chooseViewFocus,
  resolveViewAnchor,
  viewStartSource,
  viewRestoreAnnouncement,
  migrateResumeToV2,
  loadSavedViews,
  saveSavedView,
  forgetSavedViews,
  clearUserMapState,
  loadViewPrefs,
  saveViewPrefs,
  VIEW_K_MIN,
  VIEW_K_MAX,
  VIEW_ASPECT_TOLERANCE,
  VIEW_WIDTH_TOLERANCE,
  VIEW_WIDE_MIN_W,
  VIEW_WIDE_MIN_ASPECT,
  VIEW_FALLBACK_K_FLOOR,
  VIEW_WIDE_FRAME_LEFT_PX,
  VIEW_SELECTED_KEEP_FRAC,
  type SavedView,
  type ViewSlot,
  type MapResumeStateV2,
  type ViewStartWith,
  type ViewPrefs,
  type ViewAnchor,
} from './savedView.js';

export {
  mapResumeStorageKey,
  pagesDocKey,
  loadMapResume,
  saveMapResume,
  clearMapResume,
  overlayResumeOnLayout,
  softResetResume,
  isResumeStale,
  collectNodeIds,
  createDebouncedResumeSave,
  type MapResumeState,
  type MapCameraState,
  type MapNodeNudge,
  type MapResumeKeyParts,
  type ResumeLayoutLike,
  type StaleCheckResult,
  type DebouncedSave,
} from './mapResume.js';

export {
  parseLeadingTask,
  displayCaption,
  parseActionTag,
  parseThreadTag,
  toggleTaskMarker,
  taskStateOf,
  resolveTask,
  resolveAction,
  resolveThread,
  resolveNoteLinks,
  resolveJumps,
  jumpChipLabel,
  findNodeById,
  noteLinkHref,
  stripLinkTags,
  type ParsedTask,
} from './taskChrome.js';

export {
  toggleTask,
  nextTaskState,
  shouldFireAction,
} from './task.js';

export {
  clampCamToContent,
  camToEnsureVisible,
  camToFrameRects,
  followActionForFocus,
  followActionForExpand,
  visibleFractionOfRect,
  isRectComfortablyVisible,
  isRectIntersectingViewport,
  isRectFullyInvisible,
  pillWorldRect,
  unionWorldRects,
  worldRectToScreen,
  lerpCam,
  easeOutCubic,
  DEFAULT_CAM_PADDING_PX,
  DEFAULT_FOLLOW_EASE_MS,
  DEFAULT_KEEP_VISIBLE_FRAC,
  DEFAULT_RECENTRE_FRAC,
  COMFORT_INSET_PX,
  type CamState,
  type ViewportSize,
  type WorldRect,
  type FollowAction,
} from './mapCamera.js';

export {
  cleanIds,
  cleanMarkdown,
  type CleanIdsResult,
  type CleanMarkdownOptions,
} from './clean.js';
export {
  COPY_JUMP_LABEL,
  COPY_LINK_LABEL,
  COPIED_TOAST_MS,
  FOCUS_PARAM,
  NODE_HOLD_SLOP,
  NODE_ID_RE,
  NO_LINK_REASON,
  READ_ONLY_REASON,
  copiedText,
  copyText,
  copyTextFallback,
  jumpTagFor,
  nodeCopyItems,
  nodeFocusHref,
  nodeMenuKeyAction,
  placeNodeMenu,
  renderNodeMenu,
  type NodeCopyItem,
  type NodeCopyKind,
  type NodeMenuEntry,
  type NodeMenuGroup,
  type NodeMenuKeyAction,
  type NodeMenuView,
  type NodeUriOption,
} from './nodeMenu.js';
